import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { LEAD_SAFE_SELECT } from '@/lib/leadSelect'
import { callGroq, buildResearchPrompt, estimateMonthlyLeakageFallback } from '@/lib/groq'
import { getSessionFromRequest, unauthorizedResponse, hasPermission } from '@/lib/auth'

export async function POST(req: NextRequest) {
  const session = await getSessionFromRequest(req)
  if (!session) return unauthorizedResponse()
  if (!hasPermission(session.role, 'RUN_RESEARCH')) {
    return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
  }
  try {
    const { leadId } = await req.json()
    if (!leadId) return NextResponse.json({ error: 'leadId required' }, { status: 400 })
    const lead = await prisma.lead.findUnique({ where: { id: leadId }, select: LEAD_SAFE_SELECT })
    if (!lead) return NextResponse.json({ error: 'Lead not found' }, { status: 404 })

    // The research profile is structured JSON with 3 full competitor
    // objects, an industry benchmarks object, a client avatar object,
    // and two string arrays — at the default 2500-token budget this was
    // a real risk of getting cut off mid-object, which doesn't just
    // truncate the content like the audit does, it breaks JSON.parse
    // outright and fails the whole request.
    const raw = await callGroq(
      'You are a revenue intelligence analyst. Return only valid JSON. No markdown, no explanation.',
      buildResearchPrompt(lead),
      0.4,
      4000
    )
    const cleaned = raw.replace(/```json|```/g, '').trim()
    let profile
    try { profile = JSON.parse(cleaned) } catch { return NextResponse.json({ error: 'AI returned invalid JSON', raw }, { status: 500 }) }

    // Server-side safety net: if the model still omits, blanks, or writes
    // a placeholder like "N/A" for the leakage figure, compute it
    // deterministically rather than showing nothing in the dashboard.
    const leakageValue = (profile.estimatedMonthlyLeakage ?? '').toString().trim()
    if (!leakageValue || /^n\/?a$/i.test(leakageValue) || leakageValue.length < 3) {
      profile.estimatedMonthlyLeakage = estimateMonthlyLeakageFallback(lead.revenue)
      profile.leakageReasoning = profile.leakageReasoning || 'Calculated server-side as 10%-25% of stated monthly revenue (AI did not return this field).'
    }

    // This entire object is freeform JSON generated by an LLM from a
    // prompt-described schema, not a real enforced schema — JSON.parse
    // succeeding only proves it's valid JSON, not that every field the
    // dashboard expects actually exists. The dashboard's research tab
    // calls `.map()` directly on topCompetitors/strengthSignals/
    // redFlags, so a single omitted or null array field from the model
    // (more likely than it sounds — happens under safety filtering or
    // when output gets close to the token limit) crashes the whole page
    // the same way the missing `interactions` field did for the lead
    // detail view. Normalize every field the UI assumes is present.
    const normalizedProfile = {
      icpMatch: profile.icpMatch ?? 'Unknown',
      estimatedLTV: profile.estimatedLTV ?? 'Not available',
      primaryVector: profile.primaryVector ?? '1',
      vectorName: profile.vectorName ?? 'Unknown',
      topCompetitors: Array.isArray(profile.topCompetitors) ? profile.topCompetitors : [],
      industryBenchmarks: typeof profile.industryBenchmarks === 'object' && profile.industryBenchmarks ? profile.industryBenchmarks : {},
      estimatedMonthlyLeakage: profile.estimatedMonthlyLeakage,
      leakageReasoning: profile.leakageReasoning ?? '',
      closingHook: profile.closingHook ?? '',
      suggestedAuditTier: profile.suggestedAuditTier ?? 'Not available',
      marketDensity: profile.marketDensity ?? 'unknown',
      geographicOpportunity: profile.geographicOpportunity ?? '',
      gapVsTopCompetitor: profile.gapVsTopCompetitor ?? '',
      loomVector: profile.loomVector ?? '1',
      redFlags: Array.isArray(profile.redFlags) ? profile.redFlags : [],
      strengthSignals: Array.isArray(profile.strengthSignals) ? profile.strengthSignals : [],
      clientAvatar: typeof profile.clientAvatar === 'object' && profile.clientAvatar ? profile.clientAvatar : undefined,
    }

    await prisma.interaction.create({ data: { leadId, type: 'research', content: `ICP: ${normalizedProfile.icpMatch}. Vector: ${normalizedProfile.vectorName}. Leakage: ${normalizedProfile.estimatedMonthlyLeakage}. Hook: ${normalizedProfile.closingHook}` } })
    return NextResponse.json({ success: true, profile: normalizedProfile })
  } catch (error) {
    return NextResponse.json({ error: error instanceof Error ? error.message : 'Error' }, { status: 500 })
  }
}